## Electoral Democracy in India (Raw Data Filteration)

---

## Phase I

### Importing Required Python Libraries

In [2]:
import numpy as np
import pandas as pd
import statistics
import re
from sqlalchemy import create_engine

---

#### Importing the files

In [3]:
election_results_1951_2019 = pd.read_csv("RawData/election_results_1951_2019.csv")
loksabha_1962_2019 = pd.read_csv('RawData/loksabha_1962-2019.csv')
election_results_2024 = pd.read_csv('rawdata/election_results_2024.csv')
ref_party_master_1962_2021 = pd.read_csv('rawdata/ref_party_master_1962_2021.csv')
election_constituency_summary = pd.read_csv('rawdata/election_constituency_summary.csv')
socio_literacy_1951_2011 = pd.read_csv('rawdata/socio_literacy_1951_2011.csv')

#### DATAFRAME SUMMARY

In [4]:
# ELECTION RESULTS 1951 TO 2019
election_results_1951_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89840 entries, 0 to 89839
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   89829 non-null  float64
 1   state                89840 non-null  object
 2   constitution         89840 non-null  object
 3   election_year        89840 non-null  object
 4   candidate            89840 non-null  object
 5   gender               85319 non-null  object
 6   party                89824 non-null  object
 7   age                  29470 non-null  float64
 8   category             33882 non-null  object
 9   votes_received       89834 non-null  float64
 10  votes_received_perc  89811 non-null  object
 11  num_seats            89840 non-null  int64
 12  state_pc_year        89840 non-null  object
 13  rank                 89840 non-null  int64
 14  result               89840 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 10.3+ MB

In [7]:
election_results_1951_2019.head()

,id,state,constitution,election_year,candidate,gender,party,age,category,votes_received,votes_received_perc,num_seats,state_pc_year,rank,result
0,1505.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),C. MADHAV REDDY,NaN,SP,NaN,NaN,90995.0,57.99%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),1,winner
1,1506.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),J. V. NARSINGRAO,NaN,INC,NaN,NaN,65912.0,42.01%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),2,1st runner up
2,1032.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),RAGHUBIR SINGH,NaN,INC,NaN,NaN,70154.0,44.85%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,1,winner
3,1033.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),HIRDAY NAND KUNZRU,NaN,IND,NaN,NaN,47642.0,30.46%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,2,1st runner up
4,1034.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),INDER JIT,NaN,IND,NaN,NaN,16577.0,10.60%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,3,2nd runner up

In [25]:
election_results_1951_2019['party'] = election_results_1951_2019['party'].fillna('IND')

In [26]:
# ELECTION RESULTS 1951 TO 2019
election_results_1951_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89840 entries, 0 to 89839
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   89829 non-null  float64
 1   state                89840 non-null  object
 2   constitution         89840 non-null  object
 3   election_year        89840 non-null  object
 4   candidate            89840 non-null  object
 5   gender               85319 non-null  object
 6   party                89840 non-null  object
 7   age                  29470 non-null  float64
 8   category             33882 non-null  object
 9   votes_received       89840 non-null  int64
 10  votes_received_perc  89811 non-null  float64
 11  num_seats            89840 non-null  int64
 12  state_pc_year        89840 non-null  object
 13  rank                 89840 non-null  int64
 14  result               89840 non-null  object
 15  year_int             89840 non-null  int64
 16  state_upper          89840 non-null  object
 17  standardized_state   89840 non-null  object
 18  parent_state         89840 non-null  object
 19  is_winner            89840 non-null  int64
 20  is_multimember       89840 non-null  int64
dtypes: float64(3), int64(6), object(12)
memory usage: 14.4+ MB

### WORKING WITH ELECTION RESULT 1951 - 2019 (CSV FILE)

#### 1. CLEANING THE YEAR

In [5]:
# The 'election_year' looks like "1951 (1st LOK SABHA)" -> Unformatted
# Using a regular expression (regex) to extract only the 4 digits.
# Alternatively we can using string methods to do that and typecast to int but it will be very messy
def clean_election_year(year_val):
    if pd.isna(year_val):
        return None
    # Extracting the first 4-digit sequence found in the string
    match = re.search(r'\d{4}', str(year_val))
    return int(match.group()) if match else None

# Applying the cleaning function to create a new numeric year column.
election_results_1951_2019['year_int'] = election_results_1951_2019['election_year'].apply(clean_election_year)
election_results_1951_2019.head()

,id,state,constitution,election_year,candidate,gender,party,age,category,votes_received,votes_received_perc,num_seats,state_pc_year,rank,result,year_int
0,1505.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),C. MADHAV REDDY,NaN,SP,NaN,NaN,90995.0,57.99%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),1,winner,1951
1,1506.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),J. V. NARSINGRAO,NaN,INC,NaN,NaN,65912.0,42.01%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),2,1st runner up,1951
2,1032.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),RAGHUBIR SINGH,NaN,INC,NaN,NaN,70154.0,44.85%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,1,winner,1951
3,1033.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),HIRDAY NAND KUNZRU,NaN,IND,NaN,NaN,47642.0,30.46%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,2,1st runner up,1951
4,1034.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),INDER JIT,NaN,IND,NaN,NaN,16577.0,10.60%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,3,2nd runner up,1951

In [6]:
election_results_1951_2019['state'].unique()

array(['Hyderabad', 'Uttar Pradesh', 'Bombay', 'Ajmer',
       'Travancore Cochin', 'Rajasthan', 'Punjab', 'Madhya Pradesh',
       'Madras', 'Assam', 'Orissa', 'Mysore', 'West Bengal', 'Bihar',
       'Himachal Pradesh', 'Vindhya Pradesh', 'Coorg', 'Delhi',
       'Saurashtra', 'Madhya Bharat', 'Manipur', 'Patiala And East Punj',
       'Kutch', 'Bhopal', 'Tripura', 'Andhra Pradesh', 'Kerala',
       'Gujarat', 'Maharashtra', 'Haryana', 'Jammu And Kashmir',
       'Andaman And Nicobar Islands', 'Chandigarh',
       'Dadra And Nagar Haveli',
       'Laccadive, Minicoy And Amindivi Islands', 'GOA DAMAN AND DIU',
       'NAGALAND', 'Pondicherry', 'ANDAMAN AND NICOBAR ISLANDS',
       'Tamil Nadu', 'DADRA AND NAGAR HAVELI', 'Nagaland',
       'ANDHRA PRADESH', 'KERALA', 'UTTAR PRADESH', 'GUJARAT',
       'MAHARASHTRA', 'RAJASTHAN', 'WEST BENGAL', 'HARYANA', 'PUNJAB',
       'TAMIL NADU', 'BIHAR', 'ARUNACHAL PRADESH', 'ORISSA', 'ASSAM',
       'KARNATAKA', 'MADHYA PRADESH', 'CHANDIGARH',
       'NATIONAL CAPITAL TERRITORY OF DELHI', 'HIMACHAL PRADESH',
       'MANIPUR', 'LAKSHADWEEP', 'MIZORAM', 'PONDICHERRY', 'MEGHALAYA',
       'SIKKIM', 'TRIPURA', 'DAMAN AND DIU', 'GOA', 'UTTARANCHAL',
       'CHATTISGARH', 'JHARKHAND', 'Uttarkhand', 'Arunachal Pradesh',
       'Karnataka', 'Chattisgarh', 'National Capital Territory of Delhi',
       'Jharkhand', 'Lakshadweep', 'Mizoram', 'Goa', 'Meghalaya',
       'Sikkim', 'Telangana', 'Odisha'], dtype=object)

#### 2. ISOLATING UNIQUE HISTORICAL STATES

In [7]:
# This captures every variation like 'Dilli', 'Mysore', or 'Madras'[cite: 16].
unique_historical_states = sorted(election_results_1951_2019['state'].unique().tolist())

print(f"Total Unique State Entities: {len(unique_historical_states)}")
print("--- Full State List for Mapping ---")
print(unique_historical_states)

Total Unique State Entities: 86
--- Full State List for Mapping ---
['ANDAMAN AND NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'Ajmer', 'Andaman And Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'BIHAR', 'Bhopal', 'Bihar', 'Bombay', 'CHANDIGARH', 'CHATTISGARH', 'Chandigarh', 'Chattisgarh', 'Coorg', 'DADRA AND NAGAR HAVELI', 'DAMAN AND DIU', 'Dadra And Nagar Haveli', 'Delhi', 'GOA', 'GOA DAMAN AND DIU', 'GUJARAT', 'Goa', 'Gujarat', 'HARYANA', 'HIMACHAL PRADESH', 'Haryana', 'Himachal Pradesh', 'Hyderabad', 'JHARKHAND', 'Jammu And Kashmir', 'Jharkhand', 'KARNATAKA', 'KERALA', 'Karnataka', 'Kerala', 'Kutch', 'LAKSHADWEEP', 'Laccadive, Minicoy And Amindivi Islands', 'Lakshadweep', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'Madhya Bharat', 'Madhya Pradesh', 'Madras', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Mysore', 'NAGALAND', 'NATIONAL CAPITAL TERRITORY OF DELHI', 'Nagaland', 'National Capital Territory of Delhi', 'ORISSA', 'Odisha', 'Orissa', 'PONDICHERRY', 'PUNJAB', 'Patiala And East Punj', 'Pondicherry', 'Punjab', 'RAJASTHAN', 'Rajasthan', 'SIKKIM', 'Saurashtra', 'Sikkim', 'TAMIL NADU', 'TRIPURA', 'Tamil Nadu', 'Telangana', 'Travancore Cochin', 'Tripura', 'UTTAR PRADESH', 'UTTARANCHAL', 'Uttar Pradesh', 'Uttarkhand', 'Vindhya Pradesh', 'WEST BENGAL', 'West Bengal']

#### 3. CREATING THE CROSS-TABULATION (Timeline Analysis)

In [8]:
# This shows exactly which years 'Hyderabad' or 'Bombay' appear in the data[cite: 176].
# It helps you verify the 'cutoff' years for state bifurcations.
state_timeline = pd.crosstab(election_results_1951_2019['state'], election_results_1951_2019['year_int'])
state_timeline

year_int,1951,1957,1962,1967,1971,1977,1980,1984,1989,1991,1992,1996,1998,1999,2004,2009,2014,2019
state,,,,,,,,,,,,,,,,,,
ANDAMAN AND NICOBAR ISLANDS,0,0,0,0,5,2,10,6,7,5,0,11,6,5,12,11,16,16
ANDHRA PRADESH,0,0,0,0,0,165,262,298,268,609,0,1012,390,285,280,0,0,0
ARUNACHAL PRADESH,0,0,0,0,0,4,8,9,6,7,0,10,7,6,13,0,0,0
ASSAM,0,0,0,0,0,40,7,106,0,167,0,137,101,115,116,0,0,0
Ajmer,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uttar Pradesh,364,295,435,471,530,0,0,0,0,0,0,0,0,0,0,1337,1328,1029
Uttarkhand,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,76,79,57
Vindhya Pradesh,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
WEST BENGAL,0,0,0,0,0,171,272,248,336,393,0,397,272,309,358,0,0,0
West Bengal,148,101,112,137,195,0,0,0,0,0,0,0,0,0,0,368,514,508

#### Removing Stupid Hurdles

In [9]:
# 1. Normalize Case first to reduce the number of unique values
election_results_1951_2019['state_upper'] = election_results_1951_2019['state'].str.upper().str.strip()

In [10]:
# 2. Comprehensive Mapping Dictionary
# This maps historical names, spelling variations, and UT changes to modern names.
state_standardization_map = {
    # Spelling & Case Variations
    'ORISSA': 'ODISHA',
    'PONDICHERRY': 'PUDUCHERRY',
    'UTTARANCHAL': 'UTTARAKHAND',
    'UTTARKHAND': 'UTTARAKHAND',
    'CHATTISGARH': 'CHHATTISGARH',
    'NATIONAL CAPITAL TERRITORY OF DELHI': 'DELHI',
    'LACCADIVE, MINICOY AND AMINDIVI ISLANDS': 'LAKSHADWEEP',
    
    # Historical Reorganizations (1951-1956 Era)
    'HYDERABAD': 'TELANGANA', # Historical core became part of modern Telangana
    'BOMBAY': 'MAHARASHTRA',  # Note: Bombay split into MH and GJ in 1960
    'MYSORE': 'KARNATAKA',
    'MADRAS': 'TAMIL NADU',
    'TRAVANCORE COCHIN': 'KERALA',
    'SAURASHTRA': 'GUJARAT',
    'KUTCH': 'GUJARAT',
    'MADHYA BHARAT': 'MADHYA PRADESH',
    'VINDHYA PRADESH': 'MADHYA PRADESH',
    'BHOPAL': 'MADHYA PRADESH',
    'AJMER': 'RAJASTHAN',
    'COORG': 'KARNATAKA',
    'PATIALA AND EAST PUNJ': 'PUNJAB',
    'GOA DAMAN AND DIU': 'GOA' # Separated later, but helps group early data
}

In [11]:
# 3. Create the 'standardized_state' column
# We use the map; if a state isn't in the map, we keep the original upper-case name.
election_results_1951_2019['standardized_state'] = election_results_1951_2019['state_upper'].replace(state_standardization_map)

In [12]:
election_results_1951_2019.head()

,id,state,constitution,election_year,candidate,gender,party,age,category,votes_received,votes_received_perc,num_seats,state_pc_year,rank,result,year_int,state_upper,standardized_state
0,1505.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),C. MADHAV REDDY,NaN,SP,NaN,NaN,90995.0,57.99%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),1,winner,1951,HYDERABAD,TELANGANA
1,1506.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),J. V. NARSINGRAO,NaN,INC,NaN,NaN,65912.0,42.01%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),2,1st runner up,1951,HYDERABAD,TELANGANA
2,1032.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),RAGHUBIR SINGH,NaN,INC,NaN,NaN,70154.0,44.85%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH
3,1033.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),HIRDAY NAND KUNZRU,NaN,IND,NaN,NaN,47642.0,30.46%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH
4,1034.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),INDER JIT,NaN,IND,NaN,NaN,16577.0,10.60%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH

In [13]:
# 4. Handle the Parent-Child Mapping for 2000/2014 Bifurcations
# To calculate long-term volatility, we need a 'parent_state' column.
parent_state_map = {
    'UTTARAKHAND': 'UTTAR PRADESH',
    'JHARKHAND': 'BIHAR',
    'CHHATTISGARH': 'MADHYA PRADESH',
    'TELANGANA': 'ANDHRA PRADESH'
}

election_results_1951_2019['parent_state'] = election_results_1951_2019['standardized_state'].replace(parent_state_map)

print("Standardization Complete.")
print(f"Original Unique States: {len(unique_historical_states)}")
print(f"Standardized Unique States: {election_results_1951_2019['standardized_state'].nunique()}")

Standardization Complete.
Original Unique States: 86
Standardized Unique States: 36

In [14]:
election_results_1951_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89840 entries, 0 to 89839
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   89829 non-null  float64
 1   state                89840 non-null  object
 2   constitution         89840 non-null  object
 3   election_year        89840 non-null  object
 4   candidate            89840 non-null  object
 5   gender               85319 non-null  object
 6   party                89824 non-null  object
 7   age                  29470 non-null  float64
 8   category             33882 non-null  object
 9   votes_received       89834 non-null  float64
 10  votes_received_perc  89811 non-null  object
 11  num_seats            89840 non-null  int64
 12  state_pc_year        89840 non-null  object
 13  rank                 89840 non-null  int64
 14  result               89840 non-null  object
 15  year_int             89840 non-null  int64
 16  state_upper          89840 non-null  object
 17  standardized_state   89840 non-null  object
 18  parent_state         89840 non-null  object
dtypes: float64(3), int64(3), object(13)
memory usage: 13.0+ MB

In [15]:
election_results_1951_2019.head(20)

,id,state,constitution,election_year,candidate,gender,party,age,category,votes_received,votes_received_perc,num_seats,state_pc_year,rank,result,year_int,state_upper,standardized_state,parent_state
0,1505.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),C. MADHAV REDDY,NaN,SP,NaN,NaN,90995.0,57.99%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),1,winner,1951,HYDERABAD,TELANGANA,ANDHRA PRADESH
1,1506.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),J. V. NARSINGRAO,NaN,INC,NaN,NaN,65912.0,42.01%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),2,1st runner up,1951,HYDERABAD,TELANGANA,ANDHRA PRADESH
2,1032.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),RAGHUBIR SINGH,NaN,INC,NaN,NaN,70154.0,44.85%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
3,1033.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),HIRDAY NAND KUNZRU,NaN,IND,NaN,NaN,47642.0,30.46%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
4,1034.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),INDER JIT,NaN,IND,NaN,NaN,16577.0,10.60%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
5,1035.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),KRISHAN DATT PALIWAL,NaN,IND,NaN,NaN,9064.0,5.80%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,4,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
6,1036.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),BANWARI LAL,NaN,IND,NaN,NaN,6893.0,4.41%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,5,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
7,1037.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),BRIJ MOHAN SARUP,NaN,IND,NaN,NaN,6073.0,3.88%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,6,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
8,1028.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),ACHAL SINGH SETH,NaN,INC,NaN,NaN,102181.0,57.59%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
9,1029.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),KRISHAN DUTT PALIWAL,NaN,IND,NaN,NaN,45882.0,25.86%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
10,1030.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),S. C. SARKAR,NaN,BJS,NaN,NaN,18101.0,10.20%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
11,1031.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),KESHAV CHAND GUPTA,NaN,IND,NaN,NaN,11250.0,6.34%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,4,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
12,254.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),MAVLANKAR GANESH VASUDEO,NaN,INC,NaN,NaN,230778.0,31.77%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
13,255.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),VAISHYA MULDAS BHUDARDAS,NaN,INC,NaN,NaN,203928.0,28.07%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),2,winner,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
14,256.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),GOSWAMI KRISHNAJIWANJI GOKULNATHJI,NaN,RRP,NaN,NaN,112239.0,15.45%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),3,loser,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
15,257.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),PARMAR BALWANTRAI GOVINDRAI,NaN,SCF,NaN,NaN,69443.0,9.56%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),4,loser,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
16,258.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),AMIN DADUBHAI MULJIBHAI,NaN,KLP,NaN,NaN,55113.0,7.59%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),5,loser,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
17,259.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),LAXMANBHAI VALJIBHAI,NaN,KLP,NaN,NaN,54961.0,7.57%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),6,loser,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
18,286.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),KANAVADE PANDHARINATH RAMCHANDRA,NaN,INC,NaN,NaN,102300.0,55.59%,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
19,287.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),KAKDE JAGANNATH KANOJI,NaN,CPI,NaN,NaN,42935.0,23.33%,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),2,1st runner up,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA

#### 1. FIXING THE BOMBAY/GUJARAT GEOGRAPHIC TRAP

In [16]:

# We target specific districts/constituencies that were in Bombay State 
# in 1951 but are now in Gujarat to ensure Chapter 5 heatmaps are correct.
gujarat_constituencies = ['AHMEDABAD', 'MEHSANA', 'AMRELI', 'PANCH MAHALS', 'KAIRA']

def fix_bombay_split(row):
    # If the state is marked as Maharashtra (from our previous map) 
    # but the constituency is historically in Gujarat, we fix it.
    if row['standardized_state'] == 'MAHARASHTRA' and any(cn in row['constitution'].upper() for cn in gujarat_constituencies):
        return 'GUJARAT'
    return row['standardized_state']

election_results_1951_2019['standardized_state'] = election_results_1951_2019.apply(fix_bombay_split, axis=1)
election_results_1951_2019.head(20)

,id,state,constitution,election_year,candidate,gender,party,age,category,votes_received,votes_received_perc,num_seats,state_pc_year,rank,result,year_int,state_upper,standardized_state,parent_state
0,1505.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),C. MADHAV REDDY,NaN,SP,NaN,NaN,90995.0,57.99%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),1,winner,1951,HYDERABAD,TELANGANA,ANDHRA PRADESH
1,1506.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),J. V. NARSINGRAO,NaN,INC,NaN,NaN,65912.0,42.01%,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),2,1st runner up,1951,HYDERABAD,TELANGANA,ANDHRA PRADESH
2,1032.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),RAGHUBIR SINGH,NaN,INC,NaN,NaN,70154.0,44.85%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
3,1033.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),HIRDAY NAND KUNZRU,NaN,IND,NaN,NaN,47642.0,30.46%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
4,1034.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),INDER JIT,NaN,IND,NaN,NaN,16577.0,10.60%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
5,1035.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),KRISHAN DATT PALIWAL,NaN,IND,NaN,NaN,9064.0,5.80%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,4,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
6,1036.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),BANWARI LAL,NaN,IND,NaN,NaN,6893.0,4.41%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,5,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
7,1037.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),BRIJ MOHAN SARUP,NaN,IND,NaN,NaN,6073.0,3.88%,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,6,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
8,1028.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),ACHAL SINGH SETH,NaN,INC,NaN,NaN,102181.0,57.59%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
9,1029.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),KRISHAN DUTT PALIWAL,NaN,IND,NaN,NaN,45882.0,25.86%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
10,1030.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),S. C. SARKAR,NaN,BJS,NaN,NaN,18101.0,10.20%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
11,1031.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),KESHAV CHAND GUPTA,NaN,IND,NaN,NaN,11250.0,6.34%,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,4,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH
12,254.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),MAVLANKAR GANESH VASUDEO,NaN,INC,NaN,NaN,230778.0,31.77%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,GUJARAT,MAHARASHTRA
13,255.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),VAISHYA MULDAS BHUDARDAS,NaN,INC,NaN,NaN,203928.0,28.07%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),2,winner,1951,BOMBAY,GUJARAT,MAHARASHTRA
14,256.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),GOSWAMI KRISHNAJIWANJI GOKULNATHJI,NaN,RRP,NaN,NaN,112239.0,15.45%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),3,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA
15,257.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),PARMAR BALWANTRAI GOVINDRAI,NaN,SCF,NaN,NaN,69443.0,9.56%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),4,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA
16,258.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),AMIN DADUBHAI MULJIBHAI,NaN,KLP,NaN,NaN,55113.0,7.59%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),5,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA
17,259.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),LAXMANBHAI VALJIBHAI,NaN,KLP,NaN,NaN,54961.0,7.57%,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),6,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA
18,286.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),KANAVADE PANDHARINATH RAMCHANDRA,NaN,INC,NaN,NaN,102300.0,55.59%,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA
19,287.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),KAKDE JAGANNATH KANOJI,NaN,CPI,NaN,NaN,42935.0,23.33%,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),2,1st runner up,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA

#### 2. CLEANING NUMERICAL STRINGS

In [17]:
# Removing '%' and commas to allow for Chapter 6 index calculations.
election_results_1951_2019['votes_received_perc'] = (
    election_results_1951_2019['votes_received_perc']
    .astype(str)
    .str.replace('%', '', regex=False)
    .astype(float)
)

# Converting votes to numeric, handling potential commas in the string data.
election_results_1951_2019['votes_received'] = pd.to_numeric(
    election_results_1951_2019['votes_received'], errors='coerce'
).fillna(0).astype(int)

election_results_1951_2019.votes_received.head()

0    90995
1    65912
2    70154
3    47642
4    16577
Name: votes_received, dtype: int64

#### 3. CREATING A BINARY WINNER FLAG

In [18]:
# Essential for Random Forest win/loss prediction.
election_results_1951_2019['is_winner'] = (
    election_results_1951_2019['result'].str.strip().str.lower() == 'winner'
).astype(int)

In [19]:
# 4. MULTI-MEMBER CONSTITUENCY IDENTIFIER
# Helping Chapter 3 SQL queries identify 1951/1957 multi-seat logic.
election_results_1951_2019['is_multimember'] = (election_results_1951_2019['num_seats'] > 1).astype(int)

In [20]:
election_results_1951_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89840 entries, 0 to 89839
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   89829 non-null  float64
 1   state                89840 non-null  object
 2   constitution         89840 non-null  object
 3   election_year        89840 non-null  object
 4   candidate            89840 non-null  object
 5   gender               85319 non-null  object
 6   party                89824 non-null  object
 7   age                  29470 non-null  float64
 8   category             33882 non-null  object
 9   votes_received       89840 non-null  int64
 10  votes_received_perc  89811 non-null  float64
 11  num_seats            89840 non-null  int64
 12  state_pc_year        89840 non-null  object
 13  rank                 89840 non-null  int64
 14  result               89840 non-null  object
 15  year_int             89840 non-null  int64
 16  state_upper          89840 non-null  object
 17  standardized_state   89840 non-null  object
 18  parent_state         89840 non-null  object
 19  is_winner            89840 non-null  int64
 20  is_multimember       89840 non-null  int64
dtypes: float64(3), int64(6), object(12)
memory usage: 14.4+ MB

In [21]:
election_results_1951_2019.head(30)

,id,state,constitution,election_year,candidate,gender,party,age,category,votes_received,...,num_seats,state_pc_year,rank,result,year_int,state_upper,standardized_state,parent_state,is_winner,is_multimember
0,1505.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),C. MADHAV REDDY,NaN,SP,NaN,NaN,90995,...,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),1,winner,1951,HYDERABAD,TELANGANA,ANDHRA PRADESH,1,0
1,1506.0,Hyderabad,ADILABAD,1951 (1st LOK SABHA),J. V. NARSINGRAO,NaN,INC,NaN,NaN,65912,...,1,Hyderabad-ADILABAD-1951 (1st LOK SABHA),2,1st runner up,1951,HYDERABAD,TELANGANA,ANDHRA PRADESH,0,0
2,1032.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),RAGHUBIR SINGH,NaN,INC,NaN,NaN,70154,...,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,1,0
3,1033.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),HIRDAY NAND KUNZRU,NaN,IND,NaN,NaN,47642,...,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
4,1034.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),INDER JIT,NaN,IND,NaN,NaN,16577,...,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
5,1035.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),KRISHAN DATT PALIWAL,NaN,IND,NaN,NaN,9064,...,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,4,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
6,1036.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),BANWARI LAL,NaN,IND,NaN,NaN,6893,...,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,5,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
7,1037.0,Uttar Pradesh,AGRA DISTRICT (EAST),1951 (1st LOK SABHA),BRIJ MOHAN SARUP,NaN,IND,NaN,NaN,6073,...,1,Uttar Pradesh-AGRA DISTRICT (EAST)-1951 (1st L...,6,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
8,1028.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),ACHAL SINGH SETH,NaN,INC,NaN,NaN,102181,...,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,1,winner,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,1,0
9,1029.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),KRISHAN DUTT PALIWAL,NaN,IND,NaN,NaN,45882,...,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,2,1st runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
10,1030.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),S. C. SARKAR,NaN,BJS,NaN,NaN,18101,...,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,3,2nd runner up,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
11,1031.0,Uttar Pradesh,AGRA DISTRICT (WEST),1951 (1st LOK SABHA),KESHAV CHAND GUPTA,NaN,IND,NaN,NaN,11250,...,1,Uttar Pradesh-AGRA DISTRICT (WEST)-1951 (1st L...,4,loser,1951,UTTAR PRADESH,UTTAR PRADESH,UTTAR PRADESH,0,0
12,254.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),MAVLANKAR GANESH VASUDEO,NaN,INC,NaN,NaN,230778,...,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,GUJARAT,MAHARASHTRA,1,1
13,255.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),VAISHYA MULDAS BHUDARDAS,NaN,INC,NaN,NaN,203928,...,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),2,winner,1951,BOMBAY,GUJARAT,MAHARASHTRA,1,1
14,256.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),GOSWAMI KRISHNAJIWANJI GOKULNATHJI,NaN,RRP,NaN,NaN,112239,...,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),3,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA,0,1
15,257.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),PARMAR BALWANTRAI GOVINDRAI,NaN,SCF,NaN,NaN,69443,...,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),4,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA,0,1
16,258.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),AMIN DADUBHAI MULJIBHAI,NaN,KLP,NaN,NaN,55113,...,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),5,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA,0,1
17,259.0,Bombay,AHMEDABAD,1951 (1st LOK SABHA),LAXMANBHAI VALJIBHAI,NaN,KLP,NaN,NaN,54961,...,2,Bombay-AHMEDABAD-1951 (1st LOK SABHA),6,loser,1951,BOMBAY,GUJARAT,MAHARASHTRA,0,1
18,286.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),KANAVADE PANDHARINATH RAMCHANDRA,NaN,INC,NaN,NaN,102300,...,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA,1,0
19,287.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),KAKDE JAGANNATH KANOJI,NaN,CPI,NaN,NaN,42935,...,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),2,1st runner up,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA,0,0
20,288.0,Bombay,AHMEDNAGAR NORTH,1951 (1st LOK SABHA),OGALE GANGADHAR JANARDAN,NaN,SP,NaN,NaN,38789,...,1,Bombay-AHMEDNAGAR NORTH-1951 (1st LOK SABHA),3,2nd runner up,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA,0,0
21,289.0,Bombay,AHMEDNAGAR SOUTH,1951 (1st LOK SABHA),BOGAVAT UTTAMCHAND RAMCHAND,NaN,INC,NaN,NaN,88815,...,1,Bombay-AHMEDNAGAR SOUTH-1951 (1st LOK SABHA),1,winner,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA,1,0
22,290.0,Bombay,AHMEDNAGAR SOUTH,1951 (1st LOK SABHA),SATHA NAVSHERWANJI NAOROJAJI,NaN,KKP,NaN,NaN,67239,...,1,Bombay-AHMEDNAGAR SOUTH-1951 (1st LOK SABHA),2,1st runner up,1951,BOMBAY,MAHARASHTRA,MAHARASHTRA,0,0
23,1778.0,Ajmer,AJMER NORTH,1951 (1st LOK SABHA),JAWALA PRASHAD,NaN,INC,NaN,NaN,46679,...,1,Ajmer-AJMER NORTH-1951 (1st LOK SABHA),1,winner,1951,AJMER,RAJASTHAN,RAJASTHAN,1,0
24,1779.0,Ajmer,AJMER NORTH,1951 (1st LOK SABHA),CHAND KARAN,NaN,BJS,NaN,NaN,28990,...,1,Ajmer-AJMER NORTH-1951 (1st LOK SABHA),2,1st runner up,1951,AJMER,RAJASTHAN,RAJASTHAN,0,0
25,1780.0,Ajmer,AJMER NORTH,1951 (1st LOK SABHA),DINO MAL,NaN,PURP,NaN,NaN,10778,...,1,Ajmer-AJMER NORTH-1951 (1st LOK SABHA),3,2nd runner up,1951,AJMER,RAJASTHAN,RAJASTHAN,0,0
26,1781.0,Ajmer,AJMER NORTH,1951 (1st LOK SABHA),BAJORIA BADRIDAS,NaN,IND,NaN,NaN,6153,...,1,Ajmer-AJMER NORTH-1951 (1st LOK SABHA),4,loser,1951,AJMER,RAJASTHAN,RAJASTHAN,0,0
27,1782.0,Ajmer,AJMER NORTH,1951 (1st LOK SABHA),RANG RAJ MEHTA,NaN,IND,NaN,NaN,4565,...,1,Ajmer-AJMER NORTH-1951 (1st LOK SABHA),5,loser,1951,AJMER,RAJASTHAN,RAJASTHAN,0,0
28,1783.0,Ajmer,AJMER SOUTH,1951 (1st LOK SABHA),MUKAT BEHARI LAL,NaN,INC,NaN,NaN,43082,...,1,Ajmer-AJMER SOUTH-1951 (1st LOK SABHA),1,winner,1951,AJMER,RAJASTHAN,RAJASTHAN,1,0
29,1784.0,Ajmer,AJMER SOUTH,1951 (1st LOK SABHA),KUMARANAND,NaN,CPI,NaN,NaN,25128,...,1,Ajmer-AJMER SOUTH-1951 (1st LOK SABHA),2,1st runner up,1951,AJMER,RAJASTHAN,RAJASTHAN,0,0

## Minor fixes

In [27]:
# 1. FIXING THE ID COLUMN (Primary Key Preparation)
# the original 'id' has 11 nulls, we'll replace it with a clean, unique integer range to act as your MySQL Primary Key.
election_results_1951_2019['id'] = range(1, len(election_results_1951_2019) + 1)

In [28]:
# 2. FILLING NUMERICAL NaNs
# Filling missing vote percentages with 0 to ensure the ENP and 
# Volatility formulas don't return 'NaN'.
election_results_1951_2019['votes_received_perc'] = election_results_1951_2019['votes_received_perc'].fillna(0.0)

In [29]:
# 3. HANDLING MISSING CATEGORICAL DATA 
# Using placeholders for gender, age, and category to prevent SQL 'NOT NULL' errors.
election_results_1951_2019['gender'] = election_results_1951_2019['gender'].fillna('UNKNOWN')
election_results_1951_2019['age'] = election_results_1951_2019['age'].fillna(0)

# I am taking General (may affect little bit significance --> will see it later)
election_results_1951_2019['category'] = election_results_1951_2019['category'].fillna('GENERAL')

In [30]:
# 4. REFINING PARENT-STATE FOR THE BOMBAY ERA
# For the 1951 and 1957 elections, both Gujarat and Maharashtra constituencies 
# should point to 'BOMBAY' as the parent for accurate longitudinal modeling.
def refine_parent_logic(row):
    if row['year_int'] <= 1960 and row['standardized_state'] in ['GUJARAT', 'MAHARASHTRA']:
        return 'BOMBAY'
    return row['parent_state']

election_results_1951_2019['parent_state'] = election_results_1951_2019.apply(refine_parent_logic, axis=1)

print("Final Dataframe fixes applied successfully.")
election_results_1951_2019.info()

Final Dataframe fixes applied successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89840 entries, 0 to 89839
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   89840 non-null  int64
 1   state                89840 non-null  object
 2   constitution         89840 non-null  object
 3   election_year        89840 non-null  object
 4   candidate            89840 non-null  object
 5   gender               89840 non-null  object
 6   party                89840 non-null  object
 7   age                  89840 non-null  float64
 8   category             89840 non-null  object
 9   votes_received       89840 non-null  int64
 10  votes_received_perc  89840 non-null  float64
 11  num_seats            89840 non-null  int64
 12  state_pc_year        89840 non-null  object
 13  rank                 89840 non-null  int64
 14  result               89840 non-null  object
 15  year_int             89840 non-null  int64
 16  state_upper          89840 non-null  object
 17  standardized_state   89840 non-null  object
 18  parent_state         89840 non-null  object
 19  is_winner            89840 non-null  int64
 20  is_multimember       89840 non-null  int64
dtypes: float64(2), int64(7), object(12)
memory usage: 14.4+ MB

#### Exporting...

In [31]:
election_results_1951_2019.to_csv("FilteredData/election_results_1951_2019.csv")
print("Successfully Exported...")

Successfully Exported...

---

# EXPORTING TO SQL

---

In [ ]:
# Connection format: mysql+driver://username:password@host:port/database_name
# Replace 'root', 'your_password', and 'election_db' with your actual MySQL credentials
engine = create_engine('mysql+mysqlconnector://root@localhost/election_db')

# Test the connection
try:
    with engine.connect() as conn:
        print("Successfully connected to MySQL!")
except Exception as e:
    print(f"Connection failed: {e}")

Successfully connected to MySQL!

### Creating SQL file...

In [37]:
# Exporting the 1951-2019 master data
election_results_1951_2019.to_sql(
    name='election_master',      # Name of the table in MySQL
    con=engine,                  # The engine we created above
    if_exists='replace',         # 'replace' creates the table; 'append' adds to it
    index=False,                 # Do not export the Pandas index as a column
    chunksize=1000               # Sends 5000 rows at a time for efficiency
)

print("Export to MySQL Complete!")

Export to MySQL Complete!

In [8]:
# LOK SABHA RESULT FROM 1962 TO 2019 
loksabha_1962_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8047 entries, 0 to 8046
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Pc_name         8047 non-null   object
 1   no              8047 non-null   object
 2   type            8015 non-null   object
 3   state           8047 non-null   object
 4   candidate_name  8047 non-null   object
 5   party           8047 non-null   object
 6   electors        8047 non-null   object
 7   votes           8047 non-null   object
 8   Turnout         8033 non-null   object
 9   margin          8047 non-null   object
 10  margin%         8032 non-null   object
 11  year            8046 non-null   float64
dtypes: float64(1), object(11)
memory usage: 754.5+ KB

In [9]:
loksabha_1962_2019.head()

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout,margin,margin%,year
0,Adilabad,36,GEN,Andhra Pradesh,G. Narayan Reddy,Indian National Congress,"4,04,283","2,20,383",54.5 %,"89,085",40.40%,1962.0
1,Adoni,27,GEN,Andhra Pradesh,Pendekanti Venkatasubbaiah,Indian National Congress,"4,19,077","2,52,379",60.2 %,"33,022",13.10%,1962.0
2,Agra,433,GEN,Uttar Pradesh [1947 - 1999],Seth Achal Singh,Indian National Congress,"4,33,164","2,75,663",63.6 %,"54,351",19.70%,1962.0
3,Ahmedabad,120,GEN,Gujarat,Indulal Kanaiyalal Yagnik,Nutan Maha Gujarat Janta Parisha,"4,33,392","2,70,346",62.4 %,"21,592",8.00%,1962.0
4,Ahmednagar,245,GEN,Maharashtra,Motilal Kundanmal Firodya,Indian National Congress,"4,03,913","2,22,091",55.0 %,"14,038",6.30%,1962.0

In [10]:
# ELECTION RESULT 2024
election_results_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8902 entries, 0 to 8901
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   _id           8902 non-null   int64
 1   State         8902 non-null   object
 2   PC No         8902 non-null   int64
 3   PC Name       8902 non-null   object
 4   Sl no         8902 non-null   int64
 5   Candidate     8902 non-null   object
 6   Party         8902 non-null   object
 7   EVM Votes     8902 non-null   object
 8   Postal Votes  8902 non-null   object
 9   Total Votes   8902 non-null   object
 10  Vote Share    8902 non-null   object
dtypes: int64(3), object(8)
memory usage: 765.1+ KB

In [11]:
# REF MARSTER PARTIES
ref_party_master_1962_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10153 entries, 0 to 10152
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Assembly                 10153 non-null  object
 1   State_Name               10153 non-null  object
 2   Party_Name               10147 non-null  object
 3   Party_Type               7113 non-null   object
 4   Party_ID                 10147 non-null  float64
 5   Frequent_Abbreviation    10088 non-null  object
 6   Last_Abbreviation        10088 non-null  object
 7   Abbreviations            10084 non-null  object
 8   Start_Year               10152 non-null  float64
 9   Last_Year                10152 non-null  float64
 10  No_Assemblies_Contested  10153 non-null  int64
 11  Assemblies_Contested     10153 non-null  object
 12  Candidates_Contested     10153 non-null  int64
 13  Candidates_Represented   10153 non-null  int64
 14  Females_Contested        10153 non-null  int64
 15  Females_Represented      10153 non-null  int64
 16  SC_Seats_Contested       10153 non-null  int64
 17  SC_Seats_Represented     10153 non-null  int64
 18  ST_Seats_Contested       10153 non-null  int64
 19  ST_Seats_Represented     10153 non-null  int64
 20  BiPoll_Contested         10153 non-null  int64
dtypes: float64(3), int64(10), object(8)
memory usage: 1.6+ MB

In [12]:
ref_party_master_1962_2021.head()

,Assembly,State_Name,Party_Name,Party_Type,Party_ID,Frequent_Abbreviation,Last_Abbreviation,Abbreviations,Start_Year,Last_Year,...,Assemblies_Contested,Candidates_Contested,Candidates_Represented,Females_Contested,Females_Represented,SC_Seats_Contested,SC_Seats_Represented,ST_Seats_Contested,ST_Seats_Represented,BiPoll_Contested
0,Lok_Sabha,All_States,CONGRESS,National Party,3482.0,INC,INC,INC|INC(I),1962.0,2019.0,...,3|4|5|6|7|8|9|10|11|12|13|14|15|16|17,7392,3307,676,277,1091,440,585,293,235
1,Lok_Sabha,All_States,Bharatiya Janata Party,National Party,1605.0,BJP,BJP,BJP,1981.0,2019.0,...,7|8|9|10|11|12|13|14|15|16|17,3904,1601,309,161,548,228,349,144,114
2,Lok_Sabha,All_States,COMMUNIST MARXIST PARTY OF INDIA,State-based Party,14635.0,CPM,CPIM,CPM|CPI(M)|CPI (M)|CPI(Marxist),1965.0,2019.0,...,3|4|5|6|7|8|9|10|11|12|13|14|15|16|17,1003,370,78,30,154,69,76,21,20
3,Lok_Sabha,All_States,Bharatiya Lok Dal,National Party,1711.0,BLD,BLD,BLD,1977.0,1977.0,...,6,405,295,13,8,56,45,30,20,0
4,Lok_Sabha,All_States,Janata Dal,National Party,4217.0,JD,JD,JD,1989.0,1998.0,...,9|10|11|12,949,255,40,9,143,49,83,9,6

In [13]:
# ELECTION CONSTITUENCY SUMMARY REPORT
election_constituency_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21680 entries, 0 to 21679
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   State/UT & Code           21680 non-null  object
 1   Constituency Name & Code  21680 non-null  object
 2   Code Name                 21680 non-null  object
 3   Category                  21680 non-null  object
 4   Men                       5962 non-null   float64
 5   Women                     5962 non-null   float64
 6   Third Gender              5962 non-null   float64
 7   Total                     16802 non-null  float64
dtypes: float64(4), object(4)
memory usage: 1.3+ MB

In [14]:
election_constituency_summary.head()

,State/UT & Code,Constituency Name & Code,Code Name,Category,Men,Women,Third Gender,Total
0,Andhra Pradesh-S01,Araku-ST,S01_1,Candidates - Nominated,18.0,5.0,0.0,23.0
1,Andhra Pradesh-S01,Araku-ST,S01_1,Candidates - Nomination Rejected,7.0,1.0,0.0,8.0
2,Andhra Pradesh-S01,Araku-ST,S01_1,Candidates - Withdrawn,2.0,0.0,0.0,2.0
3,Andhra Pradesh-S01,Araku-ST,S01_1,Candidates - Contested,9.0,4.0,0.0,13.0
4,Andhra Pradesh-S01,Araku-ST,S01_1,Candidates - Forfeited Deposit,9.0,2.0,0.0,11.0

In [15]:
# SOCIO LITERACY RATE (CENSUS 2011)
socio_literacy_1951_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Year     7 non-null      int64
 1   Persons  7 non-null      float64
 2   Males    7 non-null      float64
 3   Females  7 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 356.0 bytes

In [16]:
socio_literacy_1951_2011.head()

   Year  Persons  Males  Females
0  1951    18.33  27.16     8.86
1  1961    28.30  40.40    15.35
2  1971    34.45  45.96    21.97
3  1981    43.57  56.38    29.76
4  1991    52.21  64.13    39.29